### ISSUE TITLE
Paper corresponds to model song2face?

### ISSUE THREAD

**Issue by TiYife** [xtliu97/VOCA-Pytorch#3]
Hello, may I ask which paper the model song2face corresponds to? 
The link in the file does not seem to be the corresponding paper for the model
https://github.com/xtliu97/audio2face-pytorch/blob/e4b987b253017043557320b41272b157c00f524d/src/model/song2face.py#L6

**Comment by xtliu97** [comment]
The paper of Song2Face could be found here: https://dl.acm.org/doi/10.1145/3410700.3425435.
The link has also been corrected in the code.

**Comment by xtliu97** [comment]
> Hello, may I ask which paper the model song2face corresponds to? The link in the file does not seem to be the corresponding paper for the model
> 
> https://github.com/xtliu97/audio2face-pytorch/blob/e4b987b253017043557320b41272b157c00f524d/src/model/song2face.py#L6

The paper of Song2Face could be found here: https://dl.acm.org/doi/10.1145/3410700.3425435.
The link has also been corrected in the code.
